name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      - name: Fix permissions for Jest
        run: chmod +x ./node_modules/.bin/jest

      # Paso 4: Ejecutar los tests
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test  # Este paso solo se ejecutará si los tests fueron exitosos

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar Webpack para crear el build
      - name: Build the project with Webpack
        run: npm run build  # Esto ejecutará Webpack y generará los archivos en /dist

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este paso solo se ejecutará si el build fue exitoso
    if: success()  # Solo si el build fue exitoso

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub para autenticar el despliegue
          publish_dir: ./dist  # El directorio donde Webpack genera el archivo bundle.js